#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OAI_ShippingRequest")]
public partial class ShippingRequestDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertShipping_Request(Shipping_Request instance);
  partial void UpdateShipping_Request(Shipping_Request instance);
  partial void DeleteShipping_Request(Shipping_Request instance);
  #endregion
	
	public ShippingRequestDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["OAI_ShippingRequestConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public ShippingRequestDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ShippingRequestDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ShippingRequestDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public ShippingRequestDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Shipping_Request> Shipping_Requests
	{
		get
		{
			return this.GetTable<Shipping_Request>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Shipping_Request")]
public partial class Shipping_Request : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _Ship_Type_Business_Private;
	
	private System.Nullable<System.DateTime> _ShipInitatingDate;
	
	private string _InitiatingDepartment;
	
	private string _From_Name;
	
	private string _To_Name;
	
	private string _To_Company;
	
	private string _To_Address_One;
	
	private string _To_Address_Two;
	
	private string _To_Phone;
	
	private string _From_Phone;
	
	private System.Nullable<System.DateTime> _Shipped_By_Date;
	
	private System.Nullable<System.TimeSpan> _Shipped_By_Time;
	
	private System.Nullable<bool> _Signature_Required;
	
	private string _Bill_To_Third_Party;
	
	private string _Logged_In_User;
	
	private string _Comments;
	
	private System.Nullable<System.DateTime> _Completed_Date;
	
	private string _From_Email_Address;
	
	private string _To_Country;
	
	private string _To_City;
	
	private string _To_State;
	
	private string _To_Postal_Code;
	
	private decimal _Original_Cost;
	
	private string _Tracking_Num;
	
	private string _Urgency;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnShip_Type_Business_PrivateChanging(string value);
    partial void OnShip_Type_Business_PrivateChanged();
    partial void OnShipInitatingDateChanging(System.Nullable<System.DateTime> value);
    partial void OnShipInitatingDateChanged();
    partial void OnInitiatingDepartmentChanging(string value);
    partial void OnInitiatingDepartmentChanged();
    partial void OnFrom_NameChanging(string value);
    partial void OnFrom_NameChanged();
    partial void OnTo_NameChanging(string value);
    partial void OnTo_NameChanged();
    partial void OnTo_CompanyChanging(string value);
    partial void OnTo_CompanyChanged();
    partial void OnTo_Address_OneChanging(string value);
    partial void OnTo_Address_OneChanged();
    partial void OnTo_Address_TwoChanging(string value);
    partial void OnTo_Address_TwoChanged();
    partial void OnTo_PhoneChanging(string value);
    partial void OnTo_PhoneChanged();
    partial void OnFrom_PhoneChanging(string value);
    partial void OnFrom_PhoneChanged();
    partial void OnShipped_By_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnShipped_By_DateChanged();
    partial void OnShipped_By_TimeChanging(System.Nullable<System.TimeSpan> value);
    partial void OnShipped_By_TimeChanged();
    partial void OnSignature_RequiredChanging(System.Nullable<bool> value);
    partial void OnSignature_RequiredChanged();
    partial void OnBill_To_Third_PartyChanging(string value);
    partial void OnBill_To_Third_PartyChanged();
    partial void OnLogged_In_UserChanging(string value);
    partial void OnLogged_In_UserChanged();
    partial void OnCommentsChanging(string value);
    partial void OnCommentsChanged();
    partial void OnCompleted_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnCompleted_DateChanged();
    partial void OnFrom_Email_AddressChanging(string value);
    partial void OnFrom_Email_AddressChanged();
    partial void OnTo_CountryChanging(string value);
    partial void OnTo_CountryChanged();
    partial void OnTo_CityChanging(string value);
    partial void OnTo_CityChanged();
    partial void OnTo_StateChanging(string value);
    partial void OnTo_StateChanged();
    partial void OnTo_Postal_CodeChanging(string value);
    partial void OnTo_Postal_CodeChanged();
    partial void OnOriginal_CostChanging(decimal value);
    partial void OnOriginal_CostChanged();
    partial void OnTracking_NumChanging(string value);
    partial void OnTracking_NumChanged();
    partial void OnUrgencyChanging(string value);
    partial void OnUrgencyChanged();
    #endregion
	
	public Shipping_Request()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ship_Type_Business_Private", DbType="NVarChar(9)")]
	public string Ship_Type_Business_Private
	{
		get
		{
			return this._Ship_Type_Business_Private;
		}
		set
		{
			if ((this._Ship_Type_Business_Private != value))
			{
				this.OnShip_Type_Business_PrivateChanging(value);
				this.SendPropertyChanging();
				this._Ship_Type_Business_Private = value;
				this.SendPropertyChanged("Ship_Type_Business_Private");
				this.OnShip_Type_Business_PrivateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipInitatingDate", DbType="Date")]
	public System.Nullable<System.DateTime> ShipInitatingDate
	{
		get
		{
			return this._ShipInitatingDate;
		}
		set
		{
			if ((this._ShipInitatingDate != value))
			{
				this.OnShipInitatingDateChanging(value);
				this.SendPropertyChanging();
				this._ShipInitatingDate = value;
				this.SendPropertyChanged("ShipInitatingDate");
				this.OnShipInitatingDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InitiatingDepartment", DbType="NVarChar(50)")]
	public string InitiatingDepartment
	{
		get
		{
			return this._InitiatingDepartment;
		}
		set
		{
			if ((this._InitiatingDepartment != value))
			{
				this.OnInitiatingDepartmentChanging(value);
				this.SendPropertyChanging();
				this._InitiatingDepartment = value;
				this.SendPropertyChanged("InitiatingDepartment");
				this.OnInitiatingDepartmentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From_Name", DbType="NVarChar(50)")]
	public string From_Name
	{
		get
		{
			return this._From_Name;
		}
		set
		{
			if ((this._From_Name != value))
			{
				this.OnFrom_NameChanging(value);
				this.SendPropertyChanging();
				this._From_Name = value;
				this.SendPropertyChanged("From_Name");
				this.OnFrom_NameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_To_Name", DbType="NVarChar(50)")]
	public string To_Name
	{
		get
		{
			return this._To_Name;
		}
		set
		{
			if ((this._To_Name != value))
			{
				this.OnTo_NameChanging(value);
				this.SendPropertyChanging();
				this._To_Name = value;
				this.SendPropertyChanged("To_Name");
				this.OnTo_NameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_To_Company", DbType="NVarChar(50)")]
	public string To_Company
	{
		get
		{
			return this._To_Company;
		}
		set
		{
			if ((this._To_Company != value))
			{
				this.OnTo_CompanyChanging(value);
				this.SendPropertyChanging();
				this._To_Company = value;
				this.SendPropertyChanged("To_Company");
				this.OnTo_CompanyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_To_Address_One", DbType="NVarChar(50)")]
	public string To_Address_One
	{
		get
		{
			return this._To_Address_One;
		}
		set
		{
			if ((this._To_Address_One != value))
			{
				this.OnTo_Address_OneChanging(value);
				this.SendPropertyChanging();
				this._To_Address_One = value;
				this.SendPropertyChanged("To_Address_One");
				this.OnTo_Address_OneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_To_Address_Two", DbType="NVarChar(50)")]
	public string To_Address_Two
	{
		get
		{
			return this._To_Address_Two;
		}
		set
		{
			if ((this._To_Address_Two != value))
			{
				this.OnTo_Address_TwoChanging(value);
				this.SendPropertyChanging();
				this._To_Address_Two = value;
				this.SendPropertyChanged("To_Address_Two");
				this.OnTo_Address_TwoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_To_Phone", DbType="NVarChar(50)")]
	public string To_Phone
	{
		get
		{
			return this._To_Phone;
		}
		set
		{
			if ((this._To_Phone != value))
			{
				this.OnTo_PhoneChanging(value);
				this.SendPropertyChanging();
				this._To_Phone = value;
				this.SendPropertyChanged("To_Phone");
				this.OnTo_PhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From_Phone", DbType="NVarChar(50)")]
	public string From_Phone
	{
		get
		{
			return this._From_Phone;
		}
		set
		{
			if ((this._From_Phone != value))
			{
				this.OnFrom_PhoneChanging(value);
				this.SendPropertyChanging();
				this._From_Phone = value;
				this.SendPropertyChanged("From_Phone");
				this.OnFrom_PhoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shipped_By_Date", DbType="Date")]
	public System.Nullable<System.DateTime> Shipped_By_Date
	{
		get
		{
			return this._Shipped_By_Date;
		}
		set
		{
			if ((this._Shipped_By_Date != value))
			{
				this.OnShipped_By_DateChanging(value);
				this.SendPropertyChanging();
				this._Shipped_By_Date = value;
				this.SendPropertyChanged("Shipped_By_Date");
				this.OnShipped_By_DateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shipped_By_Time", DbType="Time")]
	public System.Nullable<System.TimeSpan> Shipped_By_Time
	{
		get
		{
			return this._Shipped_By_Time;
		}
		set
		{
			if ((this._Shipped_By_Time != value))
			{
				this.OnShipped_By_TimeChanging(value);
				this.SendPropertyChanging();
				this._Shipped_By_Time = value;
				this.SendPropertyChanged("Shipped_By_Time");
				this.OnShipped_By_TimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Signature_Required", DbType="Bit")]
	public System.Nullable<bool> Signature_Required
	{
		get
		{
			return this._Signature_Required;
		}
		set
		{
			if ((this._Signature_Required != value))
			{
				this.OnSignature_RequiredChanging(value);
				this.SendPropertyChanging();
				this._Signature_Required = value;
				this.SendPropertyChanged("Signature_Required");
				this.OnSignature_RequiredChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bill_To_Third_Party", DbType="NVarChar(50)")]
	public string Bill_To_Third_Party
	{
		get
		{
			return this._Bill_To_Third_Party;
		}
		set
		{
			if ((this._Bill_To_Third_Party != value))
			{
				this.OnBill_To_Third_PartyChanging(value);
				this.SendPropertyChanging();
				this._Bill_To_Third_Party = value;
				this.SendPropertyChanged("Bill_To_Third_Party");
				this.OnBill_To_Third_PartyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Logged_In_User", DbType="NVarChar(50)")]
	public string Logged_In_User
	{
		get
		{
			return this._Logged_In_User;
		}
		set
		{
			if ((this._Logged_In_User != value))
			{
				this.OnLogged_In_UserChanging(value);
				this.SendPropertyChanging();
				this._Logged_In_User = value;
				this.SendPropertyChanged("Logged_In_User");
				this.OnLogged_In_UserChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comments", DbType="NVarChar(MAX)")]
	public string Comments
	{
		get
		{
			return this._Comments;
		}
		set
		{
			if ((this._Comments != value))
			{
				this.OnCommentsChanging(value);
				this.SendPropertyChanging();
				this._Comments = value;
				this.SendPropertyChanged("Comments");
				this.OnCommentsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Completed_Date", DbType="Date")]
	public System.Nullable<System.DateTime> Completed_Date
	{
		get
		{
			return this._Completed_Date;
		}
		set
		{
			if ((this._Completed_Date != value))
			{
				this.OnCompleted_DateChanging(value);
				this.SendPropertyChanging();
				this._Completed_Date = value;
				this.SendPropertyChanged("Completed_Date");
				this.OnCompleted_DateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From_Email_Address", DbType="NVarChar(50)")]
	public string From_Email_Address
	{
		get
		{
			return this._From_Email_Address;
		}
		set
		{
			if ((this._From_Email_Address != value))
			{
				this.OnFrom_Email_AddressChanging(value);
				this.SendPropertyChanging();
				this._From_Email_Address = value;
				this.SendPropertyChanged("From_Email_Address");
				this.OnFrom_Email_AddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_To_Country", DbType="NVarChar(50)")]
	public string To_Country
	{
		get
		{
			return this._To_Country;
		}
		set
		{
			if ((this._To_Country != value))
			{
				this.OnTo_CountryChanging(value);
				this.SendPropertyChanging();
				this._To_Country = value;
				this.SendPropertyChanged("To_Country");
				this.OnTo_CountryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_To_City", DbType="NVarChar(50)")]
	public string To_City
	{
		get
		{
			return this._To_City;
		}
		set
		{
			if ((this._To_City != value))
			{
				this.OnTo_CityChanging(value);
				this.SendPropertyChanging();
				this._To_City = value;
				this.SendPropertyChanged("To_City");
				this.OnTo_CityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_To_State", DbType="NVarChar(50)")]
	public string To_State
	{
		get
		{
			return this._To_State;
		}
		set
		{
			if ((this._To_State != value))
			{
				this.OnTo_StateChanging(value);
				this.SendPropertyChanging();
				this._To_State = value;
				this.SendPropertyChanged("To_State");
				this.OnTo_StateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_To_Postal_Code", DbType="NVarChar(20)")]
	public string To_Postal_Code
	{
		get
		{
			return this._To_Postal_Code;
		}
		set
		{
			if ((this._To_Postal_Code != value))
			{
				this.OnTo_Postal_CodeChanging(value);
				this.SendPropertyChanging();
				this._To_Postal_Code = value;
				this.SendPropertyChanged("To_Postal_Code");
				this.OnTo_Postal_CodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Original_Cost", DbType="Money NOT NULL")]
	public decimal Original_Cost
	{
		get
		{
			return this._Original_Cost;
		}
		set
		{
			if ((this._Original_Cost != value))
			{
				this.OnOriginal_CostChanging(value);
				this.SendPropertyChanging();
				this._Original_Cost = value;
				this.SendPropertyChanged("Original_Cost");
				this.OnOriginal_CostChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tracking_Num", DbType="NVarChar(255)")]
	public string Tracking_Num
	{
		get
		{
			return this._Tracking_Num;
		}
		set
		{
			if ((this._Tracking_Num != value))
			{
				this.OnTracking_NumChanging(value);
				this.SendPropertyChanging();
				this._Tracking_Num = value;
				this.SendPropertyChanged("Tracking_Num");
				this.OnTracking_NumChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Urgency", DbType="NChar(10)")]
	public string Urgency
	{
		get
		{
			return this._Urgency;
		}
		set
		{
			if ((this._Urgency != value))
			{
				this.OnUrgencyChanging(value);
				this.SendPropertyChanging();
				this._Urgency = value;
				this.SendPropertyChanged("Urgency");
				this.OnUrgencyChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
